### ISSUE TITLE
YouTube插件无法通过容器名配置代理

### ISSUE THREAD

**Issue by RogerRordo** [yajuhua/podcast2#19]
我服务器上部署了v2raya和podcast2镜像。YouTube插件配置http代理为 `v2raya:20171` 的话，会在下载时报错，看日志是拼接了一个奇怪的地址。配置成 `172.17.0.1:20171` 就能work。 🤔 

报错如下

```
2024-10-13 19:48:36.984  INFO 7 --- [ol-127-thread-1] i.g.y.p.y.downloader.VideoDownloader     : 执行命令: [yt-dlp, -f, m4a, --load-info-json, /tmp/1728820108139.json, --proxy, http:/v2raya/172.30.0.11:20171, --path, /data/resources, --output, 7df9982d-2dfd-41e7-987e-69965e0913a5.%(ext)s]
2024-10-13 19:48:38.862 ERROR 7 --- [ol-127-thread-1] i.g.y.p.y.downloader.VideoDownloader     : 执行异常：Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 17, in <module>
  File "yt_dlp/__init__.py", line 1081, in main
  File "yt_dlp/__init__.py", line 1069, in _real_main
  File "yt_dlp/YoutubeDL.py", line 3621, in download_with_info_file
  File "yt_dlp/YoutubeDL.py", line 3582, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 179, in wrapper
  File "yt_dlp/YoutubeDL.py", line 3483, in process_info
  File "yt_dlp/YoutubeDL.py", line 3203, in dl
  File "yt_dlp/downloader/common.py", line 466, in download
  File "yt_dlp/downloader/http.py", line 369, in real_download
  File "yt_dlp/downloader/http.py", line 120, in establish_connection
  File "yt_dlp/YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp/networking/common.py", line 130, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Invalid proxy url "http:/v2raya/172.30.0.11:20171": proxy URL with no authority: 'http:/v2raya/172.30.0.11:20171' (requests, urllib, curl_cffi), Unsupported url scheme: "https" (websockets)
[265] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by yajuhua** [comment]
不是有提示吗？
![image](https://github.com/user-attachments/assets/10937fbc-8d74-42ef-9c64-ce16fbfdca26)

**Comment by yajuhua** [comment]
目前Youtube插件不稳定，不一定能用了。

**Comment by RogerRordo** [comment]
> 不是有提示吗？
> 
> ![image](https://github.com/user-attachments/assets/10937fbc-8d74-42ef-9c64-ce16fbfdca26)
> 
> 

OK。我也是看到这个才意识到要填ip，只是不清楚不能填域名是否符合预期。此issue仅供遇到一样疑问的人参考吧。
